name: Publish Development Branch to Web

on:
  push:
    branches: [ development ]

jobs:
  dev-deploy:
    name: Deploys Development Branch to Development Website
    runs-on: ubuntu-latest

    steps:
      - name: Execute SSH commmands on remote server
        uses: JimCronqvist/action-ssh@master
        env:
          DEVDIR: ${{ secrets.DEVDIR }}
        with:
          hosts: '${{ secrets.USERNAME }}@${{ secrets.DEVHOST }}'
          privateKey: ${{ secrets.DEVKEY }}
          debug: false
          command: |
            cd $DEVDIR
            sudo -u www-data git reset --hard
            sudo -u www-data git pull